[application]
name = "Dylan Falconer"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"
[web.app]
title = "Dylan Falconer"
[web.watcher]
watch_path = ["src", "public"]
index_on_404 = false
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
